# Generated by Django 5.2.1 on 2025-05-22 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_reserva_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocheraImagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='cocheras/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web.cochera')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='inmuebles/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web.inmueble')),
            ],
        ),
    ]
