# Generated by Django 5.2.1 on 2025-05-28 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_ciudad_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='web.provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
