# Generated by Django 5.2 on 2025-05-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_delete_loginotp'),
        ('web', '0009_alter_ciudad_unique_together_alter_ciudad_id_and_more'),
    ]

    operations = [
    ]
