# Generated by Django 5.2.1 on 2025-05-31 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_loginotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebleestado',
            name='inmueble_cochera',
        ),
        migrations.AddField(
            model_name='inmuebleestado',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cochera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cochera'),
        ),
        migrations.DeleteModel(
            name='InmuebleCochera',
        ),
    ]
