# Generated by Django 5.2.1 on 2025-06-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_merge_20250602_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocheraEstado',
            fields=[
                ('id_cochera_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cochera')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estado')),
            ],
        ),
    ]
