# Generated by Django 5.2.1 on 2025-06-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_cocheraestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.perfil'),
        ),
    ]
