# Generated by Django 5.2.1 on 2025-06-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_respuestacomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestacomentario',
            name='comentario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuestacomentario', to='web.comentario'),
        ),
    ]
