# Generated by Django 5.2.1 on 2025-06-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_cochera_minimo_dias_alquiler_and_more'),
        ('web', '0019_alter_respuestacomentario_comentario'),
    ]

    operations = [
    ]
