# Generated by Django 5.2.1 on 2025-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_respuestacomentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cochera',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
