# Generated by Django 5.2.1 on 2025-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_reserva_aprobada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
