# Generated by Django 5.2.1 on 2025-06-16 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_reserva_creada_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='creada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
