# Generated by Django 5.2.1 on 2025-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_reserva_creada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_adultos',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de adultos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_ninos',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de niños'),
        ),
    ]
