# Generated by Django 5.2.1 on 2025-06-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_rename_ubicacion_cochera_direccion_and_more'),
        ('web', '0030_reserva_cantidad_adultos_reserva_cantidad_ninos'),
    ]

    operations = [
    ]
