# Generated by Django 5.2.1 on 2025-05-22 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Cochera',
            fields=[
                ('id_cochera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('cantidad_vehiculos', models.IntegerField()),
                ('con_techo', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.TextField()),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('politica_cancelacion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('cantidad_banios', models.IntegerField()),
                ('cantidad_ambientes', models.IntegerField()),
                ('cantidad_camas', models.IntegerField()),
                ('cantidad_huespedes', models.IntegerField()),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('politica_cancelacion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('cochera', models.BooleanField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.estado')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleCochera',
            fields=[
                ('id_inmueble_cochera', models.AutoField(primary_key=True, serialize=False)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cochera')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleEstado',
            fields=[
                ('id_inmueble_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estado')),
                ('inmueble_cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.inmueblecochera')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cochera')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.estado')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEstado',
            fields=[
                ('id_reserva_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_resenia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cochera')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cochera')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInmueble',
            fields=[
                ('id_cliente_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cochera')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.inmueble')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.reserva')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
