# Generated by Django 5.2.1 on 2025-05-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_usuario_rol_rename_reseña_resenia_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
    ]
