# Generated by Django 5.2.1 on 2025-05-23 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cocheraimagen_inmuebleimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
