# Generated by Django 5.2.1 on 2025-05-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_comentario_fecha_creacion'),
        ('web', '0006_loginotp'),
    ]

    operations = [
    ]
