# Generated by Django 5.2.1 on 2025-05-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_merge_0006_comentario_fecha_creacion_0006_loginotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOTP',
        ),
    ]
