# Generated by Django 5.2.1 on 2025-05-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_ciudad_provincia_cochera_ciudad_inmueble_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre', 'provincia')},
        ),
    ]
