# Generated by Django 5.2.1 on 2025-05-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
