# Generated by Django 5.2.1 on 2025-06-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_inmuebleestado_inmueble_cochera_and_more'),
        ('web', '0013_alter_notificacion_options'),
    ]

    operations = [
    ]
