# Generated by Django 5.2.1 on 2025-06-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_cochera_minimo_dias_alquiler_and_more'),
        ('web', '0018_respuestacomentario'),
    ]

    operations = [
    ]
