# Generated by Django 5.2.1 on 2025-06-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_huesped'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprobada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
