# Generated by Django 5.2 on 2025-06-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_perfil_fecha_nacimiento'),
        ('web', '0025_tarjeta'),
    ]

    operations = [
    ]
