# Generated by Django 5.2.1 on 2025-06-12 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginotp',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
