# Generated by Django 5.2.1 on 2025-06-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_loginotp_creado_en'),
        ('web', '0026_merge_0025_perfil_fecha_nacimiento_0025_tarjeta'),
    ]

    operations = [
    ]
