# Generated by Django 5.2.1 on 2025-06-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_reserva_creada_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cochera',
            old_name='ubicacion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='ubicacion',
            new_name='direccion',
        ),
    ]
