# Generated by Django 5.2.1 on 2025-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_merge_20250620_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocheraestado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebleestado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
