# Generated by Django 5.2.3 on 2025-07-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_reserva_patente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fin_original', models.DateField()),
                ('fecha_fin_nueva', models.DateField()),
                ('dias_extension', models.IntegerField()),
                ('precio_extension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('comentario_admin', models.TextField(blank=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensiones', to='web.reserva')),
            ],
            options={
                'db_table': 'extension_reserva',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
