# Generated by Django 5.2.1 on 2025-07-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_extensionreserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensionreserva',
            options={},
        ),
        migrations.RenameField(
            model_name='extensionreserva',
            old_name='fecha_respuesta',
            new_name='fecha_resolucion',
        ),
        migrations.AddField(
            model_name='extensionreserva',
            name='horas_extension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionreserva',
            name='dias_extension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionreserva',
            name='fecha_fin_nueva',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='extensionreserva',
            name='fecha_fin_original',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='extensionreserva',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='extensionreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.reserva'),
        ),
        migrations.AlterModelTable(
            name='extensionreserva',
            table=None,
        ),
    ]
