# Generated by Django 5.2.1 on 2025-07-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_extensionreserva_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extensionreserva',
            old_name='fecha_resolucion',
            new_name='fecha_respuesta',
        ),
    ]
