# Generated by Django 5.2.1 on 2025-06-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_cochera_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='web.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.perfil')),
            ],
        ),
    ]
