# Generated by Django 5.2.1 on 2025-07-07 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=100)),
                ('vencimiento', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cochera',
            fields=[
                ('id_cochera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('cantidad_vehiculos', models.IntegerField()),
                ('con_techo', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('politica_cancelacion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('minimo_dias_alquiler', models.PositiveIntegerField(default=1, verbose_name='Mínimo de días de alquiler')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.ciudad')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.estado')),
            ],
        ),
        migrations.CreateModel(
            name='CocheraImagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='cocheras/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cochera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='adminpanel.cochera')),
            ],
        ),
        migrations.CreateModel(
            name='CocheraEstado',
            fields=[
                ('id_cochera_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cochera')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField()),
                ('descripcion', models.TextField()),
                ('cantidad_banios', models.IntegerField()),
                ('cantidad_ambientes', models.IntegerField()),
                ('cantidad_camas', models.IntegerField()),
                ('cantidad_huespedes', models.IntegerField()),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('politica_cancelacion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('minimo_dias_alquiler', models.PositiveIntegerField(default=1, verbose_name='Mínimo de días de alquiler')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.ciudad')),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cochera')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.estado')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleEstado',
            fields=[
                ('id_inmueble_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.estado')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='inmuebles/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='adminpanel.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.perfil')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='inmueble',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.perfil'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cochera')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='cochera',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.perfil'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.provincia'),
        ),
        migrations.AddField(
            model_name='cochera',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.provincia'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='adminpanel.provincia'),
        ),
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id_resenia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cochera')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('cantidad_adultos', models.PositiveIntegerField(default=1, verbose_name='Cantidad de adultos')),
                ('cantidad_ninos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de niños')),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cochera')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.estado')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes', to='adminpanel.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInmueble',
            fields=[
                ('id_cliente_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('cochera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.cochera')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.inmueble')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.perfil')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEstado',
            fields=[
                ('id_reserva_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.estado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuestacomentario', to='adminpanel.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.perfil')),
            ],
        ),
    ]
